<?php
class Constants {
	const NUMBER_OF_DECIMAL_POINT = 2;
	
	const WEIGHT_DECIMAL_POINT = 0;
	
	const PAYPAL_CHARGE_PERCENTAGE = 0.035;
	
	const LANG_EN = 'en';
	const LANG_ZH = 'zh';
	
	const COOKIE_CART_ITEM = 'cart_item';
	
	const SESSION_CHECKOUT_SEESION_ID = 'SESSION_CHECKOUT_SEESION_ID';
	const SESSION_CHECKOUT_CART_ITEMS = 'SESSION_CHECKOUT_CART_ITEMS';
	const SESSION_CART_QTY = 'SESSION_CART_QTY';
	const SESSION_INVOICE_ID = 'SESSION_INVOICE_ID';
	
	const CACHE_CATEGORY_MENU = 'CACHE_CATEGORY_MENU';
}